nodeLinker: node-modules

npmPublishProvenance: true

npmRegistryServer: 'https://registry.npmjs.org'
npmPublishRegistry: "https://registry.npmjs.org"

npmScopes:
  reforge-com:
    npmRegistryServer: "https://registry.npmjs.org"
    npmPublishRegistry: "https://registry.npmjs.org"
