nodeLinker: node-modules
npmRegistryServer: 'https://registry.npmjs.org'

npmScopes:
  reforge-com:
    npmRegistryServer: "https://registry.npmjs.org"
    npmPublishRegistry: "https://registry.npmjs.org"
