name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

# Note, this comes from https://github.com/oclif/github-workflows/blob/main/.github/workflows/unitTest.yml because I couldn't figure out how to make `env` work with the default content from oclif
#
# jobs:
#   unit-tests:
#     uses: oclif/github-workflows/.github/workflows/unitTest.yml@main
#
jobs:
  unit-tests:
    env:
      REFORGE_API_KEY: ${{ secrets.REFORGE_API_KEY }}
      REFORGE_API_URL: ${{ secrets.REFORGE_API_URL }}
      REFORGE_INTEGRATION_TEST_ENCRYPTION_KEY: ${{ secrets.REFORGE_INTEGRATION_TEST_ENCRYPTION_KEY }}
      FAKE_PROD_SECRET: ${{ secrets.FAKE_PROD_SECRET }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        node_version: [lts/-1, lts/*, latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn
      - run: yarn install --immutable --network-timeout 600000
      - run: yarn format
      - run: yarn lint
      - run: yarn build
      - run: yarn test:ci
